Add tutorial search backend
deepset-ai/haystack-home pull request #119
Opened 2023-05-02 14:13 UTC by bilgeyucel

* Add vercel function to send a POST request dC
* Add example request for `/api/tutorial-search`
* Add env variables to vercel

2023-05-03 14:05 UTC, masci requested changes
Awesome! Left a couple of comments but it looks good!

2023-05-03 14:05 UTC, masci commented on api/tutorial-search.js
> +      const dcResponse = await fetch(`https://api.cloud.deepset.ai/api/v1/workspaces/${process.env.DC_WORKSPACE_NAME}/pipelines/${process.env.DC_PIPELINE_NAME}/search`, options);
nit: you can assign `https://api.cloud.deepset.ai/api/v1/workspaces` to a variable to make this line shorter, something like:
```ts
const dcResponse = await fetch(`${DC_API_URL}/${process.env.DC_WORKSPACE_NAME}/pipelines/${process.env.DC_PIPELINE_NAME}/search`, options);
```

2023-05-03 14:05 UTC, masci commented on themes/haystack/layouts/_default/tutorials.html
> +        const result = await response.text();
same as above

2023-05-03 15:39 UTC, bilgeyucel commented
> Awesome! Left a couple of comments but it looks good!

All comments are resolved! @masci

2023-05-04 06:17 UTC, masci approved these changes
Noice! Let's 🚢

2023-05-05 08:58 UTC, merged